omo Update build-release.yml

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -11,12 +11,11 @@ permissions:
   
 env:
   PROJECT_PATH: "MauiApp1.sln"
+  DOTNET_ROOT: "C:\Program Files\dotnet"
+  MSBUILD_PATH: "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
 
 jobs:
 
-# ***************************** #
-# >>>>>>> Windows build <<<<<<< #
-# ***************************** #
   maui-windows:
     runs-on: self-hosted
     steps:
@@ -25,19 +24,20 @@ jobs:
       with:
         fetch-depth: 0
 
-
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: '8.0.x'
 
-
-      # For WinUI builds
-    - name: Add msbuild to PATH
-      uses: microsoft/setup-msbuild@v2
-      with:
-        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
-      
+    - name: Verify MSBuild Path
+      shell: pwsh
+      run: |
+        if (-not (Test-Path $env:MSBUILD_PATH)) {
+          Write-Error "MSBuild path not found!"
+          exit 1
+        } else {
+          Write-Output "MSBuild found at $env:MSBUILD_PATH"
+        }
 
     - name: Generate version number using date and run number
       shell: pwsh
@@ -47,22 +47,19 @@ jobs:
         $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
         echo "APP_VERSION=$ver" >> $GITHUB_OUTPUT
 
-
     - name: Install MAUI workloads (required for GitHub-hosted runners)
       shell: pwsh
       run: dotnet workload install maui 
 
-
     - name: Restore NuGet packages
       shell: pwsh
-      run: dotnet restore ${{ env.PROJECT_PATH }}  #--configfile ${{ env.NUGETCONFIG_PATH }}
-
+      run: dotnet restore ${{ env.PROJECT_PATH }}
 
     - name: Build Maui WinUI project
       shell: pwsh
       run: |
+        $env:MSBUILD_PATH $env:PROJECT_PATH /p:Configuration=Release
         dotnet publish ${{ env.PROJECT_PATH }} -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 -p:WindowsPackageType=None -p:WindowsAppSDKSelfContained=true
-
 
     - name: Create Release
       id: create_release
@@ -75,7 +72,6 @@ jobs:
         draft: false
         prerelease: false
 
-
     - name: Upload Release Asset
       id: upload-release-asset 
       uses: actions/upload-release-asset@v1
@@ -85,4 +81,4 @@ jobs:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ./MauiApp1/bin/Release/net8.0-windows10.0.19041.0/win10-x64/publish/MauiApp1.exe
         asset_name: MauiApp1.exe
-        asset_content_type: application/evnd.microsoft.portable-executable
+        asset_content_type: application/vnd.microsoft.portable-executable
